### PR TITLE
Adding RFM69Pi schematics 

### PR DESCRIPTION
**Pull request by Basazababo**
We are using the RFM69Pi module in our relay driver, we need to  keep these schematics

### CODE REVIEW

**Comment by jlark** [comment]
Thanks Honore.

**Comment by jlark** [comment]
Can we include it as a submodule? Is this hosted on github?

**Comment by Basazababo** [comment]
Yes, 
but i did not use submodule, Am trying to read about it

**Comment by jlark** [comment]
Probably best to do that. Then we don't have to put the code in this repo and it will always be up to date.

**Comment by Basazababo** [comment]
adding submodule

**Pull request merged**
